//
// Created by Wiktor Wieclaw on 8/27/20.
//

#include "interrupt_tasks.h"

/*
 * Declarations are generated by STM32CubeMX.
 * The same stands for the calls of these functions.
 */

void HAL_GPIO_EXTI_Callback(uint16_t GPIO_Pin)
{
    switch(GPIO_Pin)
    {
        case GPIO_PIN_13:
            button_interrupt_task.resume_from_ISR();
            break;
        default:
            break;
    }
}